Repository MyongjiWay/MyongjiWay-Server, pull requests merged in 2024-08, with the labels that each got.

#31 [DOCS] 서버에 있는 .env 파일을 참조하도록 변경 (#30)
  .github/workflows/cd.yml
Labels: chore, docs

#33 [DOCS] CD.yml 수정
  .github/workflows/cd.yml
Labels: docs

#35 [DOCS] 볼륨마운트 추가
  .github/workflows/cd.yml
Labels: docs

#37 [FEAT]: Auth RestDoc 구성 및 Security 오류 수정
  .gitignore
  core/core-api/src/docs/asciidoc/auth.adoc
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/controller/AuthController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/domain/AuthService.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/domain/JwtProvider.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/jwt/JwtFilter.kt
  core/core-api/src/test/kotlin/com/myongjiway/MockMvcExtensions.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/auth/controller/AuthControllerTest.kt
  core/core-api/src/test/kotlin/com/myongjiway/token/AuthServiceTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/token/TokenAppender.kt
  core/core-domain/src/main/kotlin/com/myongjiway/token/TokenRepository.kt
  core/core-domain/src/main/kotlin/com/myongjiway/token/TokenService.kt
  core/core-domain/src/test/kotlin/com/myongjiway/token/TokenAppenderTest.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/common/BaseEntity.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/token/TokenCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/token/TokenEntity.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/token/TokenJpaRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserEntity.kt
  storage/db-core/src/main/resources/db-core.yml
  storage/db-core/src/test/kotlin/com/myongjiway/storage/db/core/token/TokenCoreRepositoryTest.kt
  storage/db-core/src/test/kotlin/com/myongjiway/storage/db/core/token/TokenEntityProxy.kt
  tests/api-docs/src/main/kotlin/com/myongjiway/test/api/RestDocsUtils.kt
Labels: feature, fix

#29 [FEAT] 공지사항 기능을 구현한다
  Dockerfile
  core/core-api/src/docs/asciidoc/index.adoc
  core/core-api/src/docs/asciidoc/notice.adoc
  core/core-api/src/docs/asciidoc/test.adoc
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/notice/controller/NoticeController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/notice/controller/v1/request/NoticeRequest.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/notice/controller/v1/request/NoticeValidator.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/notice/controller/v1/response/NoticeResponse.kt
  core/core-api/src/main/resources/application.yml
  core/core-api/src/main/resources/static/docs/index.html
  core/core-api/src/test/kotlin/com/myongjiway/notice/NoticeControllerDocsTest.kt
  core/core-api/src/test/kotlin/com/myongjiway/notice/NoticeCreateControllerTest.kt
  core/core-api/src/test/kotlin/com/myongjiway/notice/NoticeUpdateControllerTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorCode.kt
  core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorType.kt
  core/core-domain/src/main/kotlin/com/myongjiway/notice/Notice.kt
  core/core-domain/src/main/kotlin/com/myongjiway/notice/NoticeRepository.kt
  core/core-domain/src/main/kotlin/com/myongjiway/notice/NoticeService.kt
  core/core-domain/src/main/kotlin/com/myongjiway/notice/NoticeServiceImpl.kt
  core/core-domain/src/main/kotlin/com/myongjiway/notice/UserNotice.kt
  core/core-domain/src/main/kotlin/com/myongjiway/notice/UserNoticeRepository.kt
  core/core-domain/src/main/kotlin/com/myongjiway/user/User.kt
  core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeServiceCreateTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeServiceDeleteTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeServiceReadTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeServiceUpdateTest.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/NoticeCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/NoticeEntity.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/NoticeJpaRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/UserNoticeCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/UserNoticeEntity.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/UserNoticeJpaRepository.kt
  storage/db-core/src/test/resources/application.yml
Labels: feature, docs

#40 [FIX] RestDocs 오류 수정
  .github/workflows/cd.yml
  build.gradle.kts
Labels: fix

#42 [FIX] spring rest docs
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  core/core-api/build.gradle.kts
Labels: docs

#46 [ DEPLOY]: WebMvcConfig 추가 (#45)
  core/core-api/build.gradle.kts
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/WebMvcConfig.kt
Labels: deploy

#48 [HOTFIX] build.gradle.kts 의존성 수정
  .github/workflows/cd.yml
  build.gradle.kts
Labels: hotfix

#49 [DEPLOY] 배포오류 핫픽스
  .github/workflows/cd.yml
  build.gradle.kts
Labels: hotfix

#50 [HOTFIX] build.gradle.kts 의존성 수정 (#47)
  build.gradle.kts
  core/core-api/build.gradle.kts
Labels: hotfix

#51 [HOTFIX] build.gradle.kts 의존성 수정 (#47) (#50)
  build.gradle.kts
  core/core-api/build.gradle.kts
Labels: hotfix

#53 [Hotfix] build gradle fix
  .github/workflows/cd.yml
  .gitignore
  core/core-api/build.gradle.kts
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/controller/FaviconController.kt
Labels: hotfix

#54 [Hotfix] build gradle fix (#53)
  .github/workflows/cd.yml
  .gitignore
  core/core-api/build.gradle.kts
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/controller/FaviconController.kt
Labels: hotfix

#56 [FEAT] logback 설정한다.
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/JwtSecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConstants.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/WebMvcConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/jwt/JwtFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/log/RequestResponseLoggingFilter.kt
  support/logging/build.gradle.kts
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: feature

#58 [FEAT] User Inactive Api 추가 및 @AuthenticationPricipal Resolver 추가
  build.gradle.kts
  core/core-api/src/docs/asciidoc/user.adoc
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/UserController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/v1/response/UserInactiveResponseDto.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/JwtSecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/test/kotlin/com/myongjiway/MockMvcExtensions.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/UserControllerTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/user/UserRepository.kt
  core/core-domain/src/main/kotlin/com/myongjiway/user/UserService.kt
  core/core-domain/src/main/kotlin/com/myongjiway/user/UserUpdater.kt
  core/core-domain/src/test/kotlin/com/myongjiway/user/UserServiceTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/user/UserUpdaterTest.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserEntity.kt
  storage/db-core/src/test/kotlin/com/myongjiway/storage/db/core/user/UserCoreRepositoryTest.kt
  tests/api-docs/build.gradle.kts
  tests/api-docs/src/main/kotlin/com/myongjiway/test/api/PrincipalArgumentResolver.kt
  tests/api-docs/src/main/kotlin/com/myongjiway/test/api/RestDocsTest.kt
Labels: feature, fix

#64 [FEAT]: Logout API 구현
  core/core-api/src/docs/asciidoc/auth.adoc
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/controller/AuthController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/domain/JwtValidator.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/auth/controller/AuthControllerTest.kt
  core/core-api/src/test/kotlin/com/myongjiway/token/TokenTypeTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorCode.kt
  core/core-domain/src/main/kotlin/com/myongjiway/error/CoreErrorType.kt
  core/core-domain/src/main/kotlin/com/myongjiway/token/TokenProcessor.kt
  core/core-domain/src/main/kotlin/com/myongjiway/token/TokenRepository.kt
  core/core-domain/src/main/kotlin/com/myongjiway/token/TokenService.kt
  core/core-domain/src/test/kotlin/com/myongjiway/token/TokenProcessorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/token/TokenServiceTest.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/token/TokenCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/token/TokenJpaRepository.kt
  storage/db-core/src/test/kotlin/com/myongjiway/storage/db/core/token/TokenCoreRepositoryTest.kt
Labels: feature

#67 [FEAT]: 버스 위치 정보를 조회한다.
  clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/config/MqttClientConfig.kt
  core/core-api/src/docs/asciidoc/buslocation.adoc
  core/core-api/src/main/kotlin/com/myongjiway/core/buslocation/controller/v1/BusLocationController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/buslocation/controller/v1/response/GetBusLocationRes.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/buslocation/controller/v1/BusLocationControllerTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/buslocation/BusLocation.kt
  core/core-domain/src/main/kotlin/com/myongjiway/buslocation/BusLocationService.kt
  core/core-domain/src/main/kotlin/com/myongjiway/domain/buslocation/BusLocationService.kt
  core/core-domain/src/test/kotlin/com/myongjiway/buslocation/BusLocationServiceTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/domain/buslocation/BusLocationTest.kt
Labels: feature, docs, test

#69 [FEAT] LG Stack Logging (#57)
  .github/workflows/cd.yml
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: feature

#72 [DEPLOY] 배포 (#71)
  support/logging/src/main/resources/logback/logback-live.xml
Labels: deploy

#73 [FIX] error 로깅 안되는 문제 해결
  support/logging/src/main/resources/logback/logback-live.xml
Labels: fix

#75 [FEAT] prometheus 설정
  .github/workflows/cd.yml
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConstants.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/log/RequestResponseLoggingFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/notice/controller/v1/response/NoticeResponse.kt
  support/logging/src/main/resources/logback/logback-live.xml
Labels: feature

#76 [DEPLOY] 배포
  .github/workflows/cd.yml
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConstants.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/log/RequestResponseLoggingFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/notice/controller/v1/response/NoticeResponse.kt
  support/logging/src/main/resources/logback/logback-live.xml
Labels: deploy

#78 [DEPLOY] 배포
  core/core-api/src/main/kotlin/com/myongjiway/core/auth/security/config/SecurityConfig.kt
Labels: deploy

#82 [REFACTOR] 공지사항 리팩토링
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/NoticeAdminController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/NoticeController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/v1/request/NoticeRequest.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/v1/response/NoticeResponse.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeAdminControllerDocsTest.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeControllerDocsTest.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeCreateControllerTest.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeUpdateControllerTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreErrorCode.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreErrorType.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreException.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/Notice.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeCreator.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeDeleter.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeFinder.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeMetadata.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeRepository.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeService.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeUpdater.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/notice/NoticeView.kt
  core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeCreatorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeFinderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/notice/NoticeUpdaterTest.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/NoticeCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/NoticeEntity.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/notice/UserNoticeEntity.kt
Labels: refactor

#85 [REFACTOR]: 코드 정리
  clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/config/MqttClientConfig.kt
  core/core-domain/src/test/kotlin/com/myongjiway/user/UserServiceTest.kt
Labels: refactor

#88 [CHORE] 타임존 서울로 변경 (#87)
  .github/workflows/cd.yml
Labels: chore

#89 [REFACTOR] 응답 로깅 삭제, 로깅 필드 추가 (#83)
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/log/RequestResponseLoggingFilter.kt
  support/logging/src/main/resources/logback/logback-live.xml
Labels: refactor

#92 [DEPLOY] apple public key 발급 API 연동 (#91)
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleApi.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleClient.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleRestClientConfig.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/model/ApplePublicKeyResult.kt
  clients/client-apple/src/main/resources/client-apple.yml
  clients/client-apple/src/test/kotlin/com/myongjiway/ClientAppleContextTest.kt
  clients/client-apple/src/test/kotlin/com/myongjiway/ClientAppleTestApplication.kt
  clients/client-apple/src/test/resources/application.yml
  clients/client-kakao/src/test/kotlin/com/myongjiway/ClientKakaoContextTest.kt
  clients/client-kakao/src/test/kotlin/com/myongjiway/ClientKakaoTestApplication.kt
Labels: deploy

#93 [FIX] logging 에러 수정
  support/logging/src/main/resources/logback/logback-live.xml
Labels: fix

#94 [FIX] logging 에러 수정 (#93)
  support/logging/src/main/resources/logback/logback-live.xml
Labels: deploy

#95 [REFACTOR] logging
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAccessDeniedHandler.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationEntryPoint.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/log/RequestResponseLoggingFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/ApiControllerAdvice.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/LoggingAspect.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreErrorType.kt
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: refactor

#96 [DEPLOY] logging (#95)
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAccessDeniedHandler.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationEntryPoint.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/log/RequestResponseLoggingFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/ApiControllerAdvice.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/LoggingAspect.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreErrorType.kt
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: deploy

#97 [FIX] logging
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: fix

#98 [DEPLOY] logging (#97)
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: deploy

#100 [FEAT] logging
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAccessDeniedHandler.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationEntryPoint.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/ApiControllerAdvice.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/LoggingAspect.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/RequestLoggingAspect.kt
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: feature

#101 [DEPLOY] logging (#100)
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAccessDeniedHandler.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationEntryPoint.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/ApiControllerAdvice.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/LoggingAspect.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/RequestLoggingAspect.kt
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: deploy

#102 [REFACTOR]: Jwt Validator 관련 Refactoring
  clients/client-apple/build.gradle.kts
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleAuthApi.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleClient.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleRestClientConfig.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/model/ApplePublicKey.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/model/ApplePublicKeyResult.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/util/AppleJwtUtil.kt
  clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/config/MqttClientConfig.kt
  clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/util/AwsIotUtil.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/config/JwtSecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/config/SecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/domain/JwtProvider.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/domain/JwtValidator.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAccessDeniedHandler.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationEntryPoint.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/HealthController.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/token/JwtProviderTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenValidator.kt
Labels: refactor

#104 [FEAT] logging
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/RequestLoggingAspect.kt
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: feature

#106 [Deploy] 배포
  clients/client-apple/build.gradle.kts
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleAuthApi.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleClient.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/AppleRestClientConfig.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/model/ApplePublicKey.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/model/ApplePublicKeyResult.kt
  clients/client-apple/src/main/kotlin/com/myongjiway/client/apple/util/AppleJwtUtil.kt
  clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/config/MqttClientConfig.kt
  clients/client-mqtt/src/main/kotlin/com/myongjiway/client/mqtt/util/AwsIotUtil.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/config/JwtSecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/config/SecurityConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/domain/JwtProvider.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/domain/JwtValidator.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAccessDeniedHandler.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationEntryPoint.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/HealthController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/RequestLoggingAspect.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/token/JwtProviderTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenValidator.kt
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: deploy

#107 [FEAT] logging
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/NoticeAdminController.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeAdminControllerDocsTest.kt
  support/logging/src/main/resources/logback/logback-live.xml
Labels: feature

#109 [REFACTOR]: TokenValidator와 TokenGenerator 추가로 TokenService 가독성 증대 및 패키지 경로 수정
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/domain/JwtProvider.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreErrorType.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenGenerator.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenReader.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenService.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenValidator.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/user/UserReader.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/user/UserService.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/CoreDomainContextTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/CoreDomainTestApplication.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/buslocation/BusLocationServiceTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/notice/NoticeCreatorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/notice/NoticeDeleterTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/notice/NoticeFinderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/notice/NoticeUpdaterTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenAppenderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenGeneratorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenProcessorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenReaderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenServiceTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenValidatorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserAppenderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserReaderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserServiceTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserUpdaterTest.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/common/BaseEntity.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserJpaRepository.kt
  storage/db-core/src/test/kotlin/com/myongjiway/storage/db/core/user/UserCoreRepositoryTest.kt
Labels: refactor, test

#110 [FEAT] database logging
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAccessDeniedHandler.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationEntryPoint.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/config/AsyncConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/config/MdcTaskDecorator.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/RequestResponseLoggingAspect.kt
  storage/db-core/build.gradle.kts
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/config/HibernateConfig.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/config/QueryLoggingInspector.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/support/DatabaseLoggingAspect.kt
  storage/db-core/src/main/resources/db-core.yml
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: feature

#112 [DEPLOY] 배포
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/domain/JwtProvider.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAccessDeniedHandler.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationEntryPoint.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/auth/security/jwt/JwtAuthenticationFilter.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/config/AsyncConfig.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/config/MdcTaskDecorator.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/NoticeAdminController.kt
  core/core-api/src/main/kotlin/com/myongjiway/core/api/support/logging/RequestResponseLoggingAspect.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/notice/NoticeAdminControllerDocsTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/error/CoreErrorType.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenGenerator.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenReader.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenService.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/token/TokenValidator.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/user/UserReader.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/user/UserService.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/CoreDomainContextTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/CoreDomainTestApplication.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/buslocation/BusLocationServiceTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/notice/NoticeCreatorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/notice/NoticeDeleterTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/notice/NoticeFinderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/notice/NoticeUpdaterTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenAppenderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenGeneratorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenProcessorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenReaderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenServiceTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/token/TokenValidatorTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserAppenderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserReaderTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserServiceTest.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserUpdaterTest.kt
  storage/db-core/build.gradle.kts
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/common/BaseEntity.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/config/HibernateConfig.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/config/QueryLoggingInspector.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/support/DatabaseLoggingAspect.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserJpaRepository.kt
  storage/db-core/src/main/resources/db-core.yml
  storage/db-core/src/test/kotlin/com/myongjiway/storage/db/core/user/UserCoreRepositoryTest.kt
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: deploy

#114 [FIX] 쉼표 수정 (#113)
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: fix

#115 [DEPLOY] 재배포
  support/logging/src/main/resources/logback/logback-live.xml
  support/logging/src/main/resources/logback/logback-local.xml
Labels: deploy

#117 [FEAT]: 어드민 페이지 구성 및 권한 설정 완료
  core/core-api/src/main/kotlin/com/myongjiway/core/api/controller/AuthController.kt
  core/core-api/src/test/kotlin/com/myongjiway/core/api/controller/v1/auth/AuthControllerTest.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/auth/AuthService.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/auth/KakaoLoginData.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/user/UserReader.kt
  core/core-domain/src/main/kotlin/com/myongjiway/core/domain/user/UserRepository.kt
  core/core-domain/src/test/kotlin/com/myongjiway/core/domain/user/UserReaderTest.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserCoreRepository.kt
  storage/db-core/src/main/kotlin/com/myongjiway/storage/db/core/user/UserJpaRepository.kt
  storage/db-core/src/test/kotlin/com/myongjiway/storage/db/core/user/UserCoreRepositoryTest.kt
  web/build.gradle.kts
  web/src/main/kotlin/com/myongjiway/web/controller/HomeController.kt
  web/src/main/kotlin/com/myongjiway/web/controller/MainController.kt
  web/src/main/kotlin/com/myongjiway/web/security/config/SecurityConfig.kt
  web/src/main/kotlin/com/myongjiway/web/security/jwt/JwtAuthenticationFilter.kt
  web/src/main/kotlin/com/myongjiway/web/security/jwt/JwtProvider.kt
  web/src/main/kotlin/com/myongjiway/web/security/web/CustomAuthenticationFailureHandler.kt
  web/src/main/kotlin/com/myongjiway/web/security/web/CustomAuthenticationProvider.kt
  web/src/main/kotlin/com/myongjiway/web/security/web/CustomAuthenticationSuccessHandler.kt
  web/src/main/kotlin/com/myongjiway/web/security/web/CustomUserDetailsService.kt
  web/src/main/kotlin/com/myongjiway/web/security/web/UserPrincipal.kt
  web/src/main/resources/static/css/styles.css
  web/src/main/resources/templates/home.html
  web/src/main/resources/templates/login.html
  web/src/main/resources/templates/notices/list.html
Labels: feature
